name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd /home/runner/work/nbl-bookstore/nbl-bookstore
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Wait for MySQL to initialize
      run: |
        until mysqladmin ping -h127.0.0.1 --silent; do sleep 1; done

    - name: Create the database
      run: |
        mysql -h 127.0.0.1 -uroot -p1234 -e "CREATE DATABASE IF NOT EXISTS testdb;"

    - name: Run tests
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: root
        MYSQL_PASSWORD: 1234
        MYSQL_DATABASE: testdb
      run: |
        cd /home/runner/work/nbl-bookstore/nbl-bookstore
        python -m unittest discover -s tests
